name: Destroy PR

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  destroy:
    name: Destroy PR
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_environment: "development"
      TF_VAR_region: "eu-central-1"
      TF_VAR_aws_account_id: 746669194690
      TF_VAR_pr_number: ${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          terraform_wrapper: false
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        id: oidc
        with:
          role-to-assume: arn:aws:iam::746669194690:role/TerraformExecutionRole
          aws-region: eu-central-1
          audience: sts.amazonaws.com 

      - name: Terraform Init (Prepare for Destroy)
        working-directory: src/entry
        run: |
          terraform init \
            -backend-config="region=eu-central-1" \
            -backend-config="bucket=terraform-state-terminapp-dev" \
            -backend-config="key=pr-${{ github.event.number }}/state.tfstate" \
            -backend-config="use_lockfile=true"

      - name: Terraform Destroy
        working-directory: src/entry
        run: terraform destroy -auto-approve