name: Destroy Terraform Stating Environment

on:
  workflow_dispatch:

jobs:
  terraform-destroy-staging:
    name: Destroy Terraform Staging Environment
    runs-on: ubuntu-latest
    environment: staging
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      TF_VAR_environment: "staging"
      TF_VAR_region: ${{ vars.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          terraform_wrapper: false

      - name: Terraform Init (Prepare for Destroy)
        working-directory: infrastructure/environments/general
        run: |
          terraform init \
            -backend-config="region=${{ vars.AWS_DEFAULT_REGION }}" \
            -backend-config="bucket=${{ vars.s3_bucket_name }}" \
            -backend-config="key=state.tfstate" \
            -backend-config="encrypt=true" \
            -backend-config="use_lockfile=true"

      - name: Terraform Destroy
        working-directory: infrastructure/environments/general
        run: terraform destroy -auto-approve