name: Destroy Terraform Dev Environment

on:
  pull_request:
    types: [closed]

jobs:
  terraform-destroy-dev:
    name: Destroy Terraform Dev Environment (PR Closed)
    runs-on: ubuntu-latest
    environment: development
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      TF_VAR_environment: "development"
      TF_VAR_region: ${{ vars.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          terraform_wrapper: false

      - name: Set Unique State Key for PR
        id: set-key
        run: echo "TF_STATE_KEY=development/state-pr-${{ github.event.pull_request.number }}.tfstate" >> $GITHUB_ENV

      - name: Terraform Init (Prepare for Destroy)
        working-directory: infrastructure/environments/general
        run: |
          terraform init \
            -backend-config="region=${{ vars.AWS_DEFAULT_REGION }}" \
            -backend-config="bucket=${{ vars.s3_bucket_name }}" \
            -backend-config="key=${TF_STATE_KEY}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ vars.dynamodb_table_name }}"

      - name: Terraform Destroy
        working-directory: infrastructure/environments/general
        run: terraform destroy -auto-approve

      - name: Delete Lock from DynamoDB
        run: |
          LOCK_ID="${{ vars.s3_bucket_name }}/${TF_STATE_KEY}"
          echo "Attempting to delete lock: $LOCK_ID from table: ${{ vars.dynamodb_table_name }}"
          aws dynamodb delete-item \
            --table-name ${{ vars.dynamodb_table_name }} \
            --key "{\"LockID\":{\"S\":\"$LOCK_ID\"}}" \
            --region ${{ vars.AWS_DEFAULT_REGION }} \
            || echo "Lock not found or already released."