name: Infrastructure Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - published
  pull_request:

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    environment: development
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    defaults:
      run:
        working-directory: infrastructure/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Check tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} =~ ^refs\/tags\/v[0-9]+\.[0-9]+\.[0-9]+$ ]] && [[ ${{ github.event_name }} == 'release' ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "environment=development" >> $GITHUB_OUTPUT
          else
            echo "environment=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Debug Name Variable
        run: |
          echo "name: ${{ vars.NAME }}"

      - name: Terraform Init and Plan and Apply Development
        if: steps.check-tag.outputs.environment == 'development'
        env:
          TF_VAR_environment: "dev"
          TF_VAR_region: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_VAR_s3_bucket_name: ${{ secrets.s3_bucket_name }}
          TF_VAR_dynamodb_table_name: ${{ secrets.dynamodb_table }}
        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve

      - name: Terraform Init and Plan and Apply Production
        if: steps.check-tag.outputs.environment == 'production'
        env:
          TF_VAR_environment: "prod"
          TF_VAR_region: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_VAR_s3_bucket_name: ${{ secrets.s3_bucket_name }}
          TF_VAR_dynamodb_table_name: ${{ secrets.dynamodb_table }}
        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve

  terraform-environments:
    name: Terraform Environments
    runs-on: ubuntu-latest
    needs: deploy-backend
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Check tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} =~ ^refs\/tags\/v[0-9]+\.[0-9]+\.[0-9]+$ ]] && [[ ${{ github.event_name }} == 'release' ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "environment=development" >> $GITHUB_OUTPUT
          else
            echo "environment=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Init and Plan Development
        if: steps.check-tag.outputs.environment == 'development'
        working-directory: infrastructure/environments/dev
        env:
          TF_VAR_environment: "dev"
          TF_VAR_region: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          terraform init \
            -backend-config="region=${{secrets.AWS_DEFAULT_REGION}}" \
            -backend-config="bucket=${{ secrets.s3_bucket_name }}" \
            -backend-config="key=state.tfstate" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ secrets.dynamodb_table }}"
          terraform plan

      - name: Terraform Apply Development
        if: steps.check-tag.outputs.environment == 'development'
        working-directory: infrastructure/environments/dev
        run: terraform apply -auto-approve

      - name: Terraform Init and Plan Production
        if: steps.check-tag.outputs.environment == 'production'
        working-directory: infrastructure/environments/prod
        env:
          TF_VAR_environment: "prod"
          TF_VAR_region: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          terraform init \
            -backend-config="region=${{secrets.AWS_DEFAULT_REGION}}" \
            -backend-config="bucket=${{ secrets.s3_bucket_name }}" \
            -backend-config="key=state.tfstate" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ secrets.dynamodb_table }}"
          terraform plan

      - name: Terraform Apply Production
        if: steps.check-tag.outputs.environment == 'production'
        working-directory: infrastructure/environments/prod
        run: terraform apply -auto-approve