name: Infrastructure Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - published
  pull_request:

jobs:
  deploy-backend-dev:
    name: Deploy Backend (Dev)
    runs-on: ubuntu-latest
    environment: development
    if: github.ref == 'refs/heads/main'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    defaults:
      run:
        working-directory: infrastructure/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init and Plan and Apply
        env:
          TF_VAR_environment: "dev"
          TF_VAR_region: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_VAR_s3_bucket_name: ${{ secrets.s3_bucket_name }}
          TF_VAR_dynamodb_table_name: ${{ secrets.dynamodb_table }}
        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve

  deploy-backend-prod:
    name: Deploy Backend (Prod)
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'release'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    defaults:
      run:
        working-directory: infrastructure/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check
    
      - name: Terraform Init and Plan and Apply
        env:
          TF_VAR_environment: "prod"
          TF_VAR_region: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_VAR_s3_bucket_name: ${{ secrets.s3_bucket_name }}
          TF_VAR_dynamodb_table_name: ${{ secrets.dynamodb_table }}
        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve

  terraform-environments-dev:
    name: Terraform Environments
    runs-on: ubuntu-latest
    needs: deploy-backend-dev
    environment: development
    if: github.ref == 'refs/heads/main'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Init and Plan Development
        working-directory: infrastructure/environments/dev
        env:
          TF_VAR_environment: "dev"
          TF_VAR_region: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          terraform init \
            -backend-config="region=${{secrets.AWS_DEFAULT_REGION}}" \
            -backend-config="bucket=${{ secrets.s3_bucket_name }}" \
            -backend-config="key=state.tfstate" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ secrets.dynamodb_table }}"
          terraform plan

      - name: Terraform Apply Development
        working-directory: infrastructure/environments/dev
        run: terraform apply -auto-approve

  terraform-environments-prod:
    name: Terraform Environments
    runs-on: ubuntu-latest
    needs: deploy-backend-prod
    environment: production
    if: github.event_name == 'release'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Init and Plan Production
        working-directory: infrastructure/environments/prod
        env:
          TF_VAR_environment: "prod"
          TF_VAR_region: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          terraform init \
            -backend-config="region=${{secrets.AWS_DEFAULT_REGION}}" \
            -backend-config="bucket=${{ secrets.s3_bucket_name }}" \
            -backend-config="key=state.tfstate" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ secrets.dynamodb_table }}"
          terraform plan

      - name: Terraform Apply Production
        working-directory: infrastructure/environments/prod
        run: terraform apply -auto-approve