name: Provision Infrastructure 

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - published
  pull_request:

jobs:
  terraform-environments-dev:
    name: Terraform Environments (Development)
    runs-on: ubuntu-latest
    environment: development
    if: github.event_name == 'pull_request'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_environment: "development"
      TF_VAR_region: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Set Unique State Key
        id: set-key
        run: echo "TF_STATE_KEY=development/state-pr-${{ github.event.pull_request.number }}.tfstate" >> $GITHUB_ENV

      - name: Terraform Init and Plan Development
        working-directory: infrastructure/environments/general
        run: |
          terraform init \
            -backend-config="region=${{ secrets.AWS_DEFAULT_REGION }}" \
            -backend-config="bucket=${{ secrets.s3_bucket_name }}" \
            -backend-config="key=${TF_STATE_KEY}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ secrets.dynamodb_table_name }}"
          terraform plan

      - name: Terraform Apply Development
        id: apply-step
        working-directory: infrastructure/environments/general
        continue-on-error: true
        run: terraform apply -auto-approve

      - name: Terraform Destroy on Failure
        if: steps.apply-step.outcome == 'failure'
        working-directory: infrastructure/environments/general
        run: |
          echo "Terraform apply failed. Starting destroy to clean up."
          terraform destroy -auto-approve

  terraform-environments-staging:
    name: Terraform Environments
    runs-on: ubuntu-latest
    environment: staging
    if: github.ref == 'refs/heads/main'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_environment: "staging"
      TF_VAR_region: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Init and Plan Staging
        working-directory: infrastructure/environments/general
        run: |
          terraform init \
            -backend-config="region=${{secrets.AWS_DEFAULT_REGION}}" \
            -backend-config="bucket=${{ secrets.s3_bucket_name }}" \
            -backend-config="key=staging/state.tfstate" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ secrets.dynamodb_table_name }}"
          terraform plan

      - name: Terraform Apply Staging
        id: apply-step
        working-directory: infrastructure/environments/general
        continue-on-error: true
        run: terraform apply -auto-approve

      - name: Terraform Destroy on Failure
        if: steps.apply-step.outcome == 'failure'
        working-directory: infrastructure/environments/general
        run: |
          echo "Terraform apply failed. Starting destroy to clean up."
          terraform destroy -auto-approve

  terraform-environments-prod:
    name: Terraform Environments
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'release'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_environment: "production"
      TF_VAR_region: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Init and Plan Production
        working-directory: infrastructure/environments/general
        run: |
          terraform init \
            -backend-config="region=${{secrets.AWS_DEFAULT_REGION}}" \
            -backend-config="bucket=${{ secrets.s3_bucket_name }}" \
            -backend-config="key=production/state.tfstate" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ secrets.dynamodb_table_name }}"
          terraform plan

      - name: Terraform Apply Production
        id: apply-step
        working-directory: infrastructure/environments/general
        continue-on-error: true
        run: terraform apply -auto-approve

      - name: Terraform Destroy on Failure
        if: steps.apply-step.outcome == 'failure'
        working-directory: infrastructure/environments/general
        run: |
          echo "Terraform apply failed. Starting destroy to clean up."
          terraform destroy -auto-approve